#pragma once

#include <QWidget>
#include "ui_FeedScreen.h"
#include <Camera.h>
#include <opencv2/core/utility.hpp>
#include "opencv2/cudaobjdetect.hpp"
#include "opencv2/highgui.hpp"
#include "opencv2/objdetect.hpp"
#include "opencv2/imgproc.hpp"
#include "opencv2/ml.hpp"
#include "opencv2\cudabgsegm.hpp"
#include <opencv2/core/utility.hpp>
#include "opencv2/video/tracking.hpp"
#include "opencv2/imgproc.hpp"
#include "opencv2/videoio.hpp"
#include "opencv2/highgui.hpp"
#include "opencv2/imgcodecs.hpp"
#include <opencv2/video.hpp>
#include "DetectSVM.h"
#include "DetectHOG.h"
#include "Anomaly.h"
#include <QtWidgets/QMainWindow>
#include <QSharedPointer>
#include <qtimer.h>
#include <iostream>
#include <fstream>
#include <string>
#include <sstream>
#include <iomanip>
#include <stdexcept>

class FeedScreen : public QWidget
{
	Q_OBJECT

public:
	FeedScreen(QWidget *parent = Q_NULLPTR);
	~FeedScreen();
	vector<vector<Point>> BackGroundSub();
	void SetParameters(double,double,int,int);
	void resetParameters();
	void update(Camera*);
	string workFps() const;
	void workEnd();
	Mat GetProcessedFrame();

public slots:
	void refresh();
	void startFeed(string location);


private:
	Ui::FeedScreen ui;
	cv::VideoCapture capture;
	Mat frame;
	int frameCount = 0;
	QImage VFrame;
	QTimer* tmrTimer;
	bool backprojMode;
	bool selectObject;
	int trackObject;
	bool showHist;
	Point origin;
	Rect selection;
	int vmin;
	int vmax;
	int smin;
	Mat src;
	Mat hsv;
	Mat hue;
	int bins = 25;
	DetectSVM * detector;
	Mat frameGray;
	string CamNumOrVidLocation;
	cuda::GpuMat frame_g;//current frame
	Mat resize_blur_Img;
	Mat fgMaskMOG2; //fg mask fg mask generated by MOG2 method
	cuda::GpuMat fgMaskMOG2_g;
	Mat binaryImg;
	Mat ContourImg; //fg mask fg mask generated by MOG2 method
	Ptr <cv::cuda::BackgroundSubtractorMOG2> cudaMOG2 = cv::cuda::createBackgroundSubtractorMOG2(300, 32, true); //cuda background sub								 
	Mat element = getStructuringElement(MORPH_RECT, Size(7, 7), Point(3, 3)); //morphology element
	string work_fps="";
	int64 work_begin;
	string OldResults = "";
	int refreshCount = 0;
};